// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/installations": {
            "get": {
                "description": "Returns all GitHub App installations tracked by this service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "installations"
                ],
                "summary": "List all GitHub App installations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ghub.InstallationResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/installations/{installation_id}/repos": {
            "get": {
                "description": "Returns all repositories associated with a GitHub App installation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List repositories for an installation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "GitHub Installation ID",
                        "name": "installation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ghub.RepositoryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/installations/{installation_id}/repos/sync": {
            "post": {
                "description": "Fetches the latest repos from GitHub API and upserts them",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Sync repositories from GitHub",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "GitHub Installation ID",
                        "name": "installation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ghub.RepositoryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/links": {
            "get": {
                "description": "Returns the repository link configuration for a given project ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-links"
                ],
                "summary": "Get the repository link for a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ghub.ProjectRepoLinkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/links/{id}": {
            "delete": {
                "description": "Removes a specific project-repo link",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-links"
                ],
                "summary": "Delete a project-repo link by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Link UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ghub.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos": {
            "get": {
                "description": "Returns all tracked repositories, optionally filtered by installation_id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List all repositories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by installation ID",
                        "name": "installation_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ghub.RepositoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/archive": {
            "get": {
                "description": "Returns a signed archive URL and token for build workers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo-access"
                ],
                "summary": "Get authenticated archive URL for a repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository UUID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ghub.RepoAccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/clone-url": {
            "get": {
                "description": "Returns an authenticated clone URL and token for build workers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo-access"
                ],
                "summary": "Get authenticated clone URL for a repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository UUID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ghub.RepoAccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/link": {
            "post": {
                "description": "Binds a repository to a deployment project for auto-deploy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-links"
                ],
                "summary": "Link a repository to a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository UUID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Link configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ghub.LinkRepoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ghub.ProjectRepoLinkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes the deployment binding for a repository",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project-links"
                ],
                "summary": "Unlink a repository from its project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository UUID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ghub.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns API health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns dependency readiness status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.ReadyResponse"
                        }
                    }
                }
            }
        },
        "/webhooks/github": {
            "post": {
                "description": "Receives and processes webhook events from GitHub (push, installation, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Handle GitHub webhook events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ghub.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ghub.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ghub.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "ghub.InstallationResponse": {
            "type": "object",
            "properties": {
                "account_login": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "installation_id": {
                    "type": "integer"
                },
                "suspended": {
                    "type": "boolean"
                }
            }
        },
        "ghub.LinkRepoRequest": {
            "type": "object",
            "properties": {
                "auto_deploy": {
                    "type": "boolean"
                },
                "branch": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "ghub.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "success message"
                }
            }
        },
        "ghub.ProjectRepoLinkResponse": {
            "type": "object",
            "properties": {
                "auto_deploy": {
                    "type": "boolean"
                },
                "branch": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "repository": {
                    "$ref": "#/definitions/ghub.RepositoryResponse"
                }
            }
        },
        "ghub.RepoAccessResponse": {
            "type": "object",
            "properties": {
                "archive_url": {
                    "type": "string"
                },
                "clone_url": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "ghub.RepositoryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "default_branch": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "github_repo_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "installation_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                }
            }
        },
        "health.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "health.ReadyResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "ok"
                },
                "environment": {
                    "type": "string",
                    "example": "production"
                },
                "kafka": {
                    "type": "string",
                    "example": "ok"
                },
                "smtp": {
                    "type": "string",
                    "example": "ok"
                },
                "status": {
                    "type": "string",
                    "example": "ready"
                },
                "template_dir": {
                    "type": "string",
                    "example": "templates"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GitHub Integration API",
	Description:      "GitHub App webhook + repo management service for kr0n.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
