export const DOCS_VERSION = "1.0.4";
export const DOCS_PROTOCOL = "KRON_RUNTIME_V1";

export const DOCS_SECTIONS = [
  {
    id: "quick-start",
    title: "Quick Start",
    eyebrow: "GETTING STARTED // PROTOCOL 1.0.4",
    slug: "/docs/quick-start",
    shortDesc: "Initialize, configure, and dispatch your first edge deployment in under 60 seconds.",
    symbol: "⚡",
    badge: "CORE_BOOT",
    latency: "< 1.2s",
    status: "OPERATIONAL",
    subsections: [
      { id: "overview", title: "Platform Overview" },
      { id: "prerequisites", title: "Prerequisites" },
      { id: "connect-repo", title: "1. Connect Repository" },
      { id: "environment", title: "2. Configure Environment" },
      { id: "build-pipeline", title: "3. Build & AST Pipeline" },
      { id: "edge-dispatch", title: "4. Global Edge Dispatch" },
      { id: "canvas-workspace", title: "Spatial Canvas Workspace" },
    ],
  },
  {
    id: "ai",
    title: "AI & Engine Intelligence",
    eyebrow: "AUTONOMOUS HEURISTICS // REFRACTION ENGINE",
    slug: "/docs/ai",
    shortDesc: "Automated syntax tree analysis, predictive cold-start caching, and edge routing heuristics.",
    symbol: "◈",
    badge: "NEURAL_AST",
    latency: "AUTOMATIC",
    status: "ACTIVE",
    subsections: [
      { id: "overview", title: "Engine Intelligence" },
      { id: "ast-analysis", title: "AST Dependency Analysis" },
      { id: "predictive-caching", title: "Predictive Cold-Start Caching" },
      { id: "microfrontend-routing", title: "Adaptive Edge Routing" },
      { id: "log-heuristics", title: "Log Anomaly Detection" },
      { id: "runtime-metrics", title: "Health States & Telemetry" },
    ],
  },
  {
    id: "cli",
    title: "CLI Tooling",
    eyebrow: "DEVELOPER TOOLING // $ KRON CLI",
    slug: "/docs/cli",
    shortDesc: "Terminal-first workflows for local import, instant deployment, live log streaming, and secret sync.",
    symbol: "❯_",
    badge: "TERMINAL_V1",
    latency: "INSTANT",
    status: "STABLE",
    subsections: [
      { id: "installation", title: "Installation" },
      { id: "authentication", title: "Authentication" },
      { id: "import-local", title: "Local Import (kron import)" },
      { id: "deploy", title: "Deploy (kron deploy)" },
      { id: "logs", title: "Live Logs (kron logs)" },
      { id: "env-management", title: "Environment Sync (kron env)" },
      { id: "flag-reference", title: "Command Reference Matrix" },
    ],
  },
  {
    id: "templates",
    title: "Templates & Starters",
    eyebrow: "MODULAR STARTERS // REPOSITORY BLUEPRINTS",
    slug: "/docs/templates",
    shortDesc: "Production-ready architectures optimized for instant edge compilation and zero cold-start latency.",
    symbol: "⬡",
    badge: "STARTER_PACK",
    latency: "0-CONFIG",
    status: "VERIFIED",
    subsections: [
      { id: "overview", title: "Ecosystem Starters" },
      { id: "nucleus-engine", title: "nucleus-engine (Core Runtime)" },
      { id: "quantum-web", title: "quantum-web (Edge SSR)" },
      { id: "auth-service", title: "auth-service (WASM Token Auth)" },
      { id: "obsidian-design", title: "obsidian-design-system" },
      { id: "legacy-dash", title: "legacy-dash (Observability)" },
      { id: "manifest", title: "kron.config.json Manifest" },
    ],
  },
];

export const SEARCH_INDEX = [
  {
    title: "Quick Start: Platform Overview",
    section: "Quick Start",
    slug: "/docs/quick-start#overview",
    snippet: "Understand the kr0n execution model, zero-config build pipeline, and edge deployment lifecycle.",
    keywords: ["quick start", "getting started", "deploy", "setup", "workflow", "overview"],
  },
  {
    title: "Quick Start: Connect Repository",
    section: "Quick Start",
    slug: "/docs/quick-start#connect-repo",
    snippet: "Import GitHub or local repositories via the dashboard or CLI to trigger automated builds.",
    keywords: ["git", "github", "repository", "import", "branch", "main"],
  },
  {
    title: "Quick Start: Build & AST Pipeline",
    section: "Quick Start",
    slug: "/docs/quick-start#build-pipeline",
    snippet: "Inspect the BUILD_LOG_STREAM_V1 pipeline: dependencies, AST parsing, asset optimization, and edge deployment.",
    keywords: ["build", "pipeline", "logs", "stream", "ast", "deploy"],
  },
  {
    title: "AI: AST Dependency Analysis",
    section: "AI",
    slug: "/docs/ai#ast-analysis",
    snippet: "Automated syntax tree parsing that prunes unused code and validates edge-compatible runtime primitives.",
    keywords: ["ast", "analysis", "ai", "syntax tree", "compiler", "pruning", "optimization"],
  },
  {
    title: "AI: Predictive Cold-Start Caching",
    section: "AI",
    slug: "/docs/ai#predictive-caching",
    snippet: "Heuristic pre-warming of global edge nodes based on real-time traffic velocity and regional demand.",
    keywords: ["cold start", "cache", "predictive", "latency", "edge", "pre-warming"],
  },
  {
    title: "AI: Adaptive Microfrontend Routing",
    section: "AI",
    slug: "/docs/ai#microfrontend-routing",
    snippet: "Dynamic incoming request inspection and automated traffic dispatch across origin servers.",
    keywords: ["routing", "microfrontends", "traffic", "origin", "edge requests"],
  },
  {
    title: "CLI: Installation & Setup",
    section: "CLI",
    slug: "/docs/cli#installation",
    snippet: "Install the official @kr0n/cli package globally via npm, yarn, or direct curl install script.",
    keywords: ["cli", "install", "npm", "curl", "setup", "terminal"],
  },
  {
    title: "CLI: Local Import (kron import --local)",
    section: "CLI",
    slug: "/docs/cli#import-local",
    snippet: "Link a local repository directly to the kr0n platform without manual web configuration.",
    keywords: ["kron import", "local", "import --local", "link", "folder", "terminal"],
  },
  {
    title: "CLI: Deployment Command (kron deploy)",
    section: "CLI",
    slug: "/docs/cli#deploy",
    snippet: "Push local commits to production, stream live build logs, and receive instant preview URLs.",
    keywords: ["kron deploy", "deploy", "production", "preview", "push"],
  },
  {
    title: "CLI: Environment Sync (kron env)",
    section: "CLI",
    slug: "/docs/cli#env-management",
    snippet: "Manage encrypted environment variables and secrets directly from the command line.",
    keywords: ["kron env", "secrets", "environment", "variables", "keys"],
  },
  {
    title: "Templates: nucleus-engine",
    section: "Templates",
    slug: "/docs/templates#nucleus-engine",
    snippet: "Core high-throughput backend service template with refraction engine integration.",
    keywords: ["nucleus-engine", "template", "backend", "refraction", "starter"],
  },
  {
    title: "Templates: quantum-web",
    section: "Templates",
    slug: "/docs/templates#quantum-web",
    snippet: "Edge SSR Web application starter with hydration protection and global asset distribution.",
    keywords: ["quantum-web", "template", "ssr", "react", "nextjs", "frontend"],
  },
  {
    title: "Templates: auth-service",
    section: "Templates",
    slug: "/docs/templates#auth-service",
    snippet: "WebAssembly token authentication and session verification microservice starter.",
    keywords: ["auth-service", "template", "wasm", "auth", "token", "jwt"],
  },
  {
    title: "Templates: obsidian-design-system",
    section: "Templates",
    slug: "/docs/templates#obsidian-design",
    snippet: "Futuristic brutalist UI component library with clipped-corner geometry and dark mode tokens.",
    keywords: ["obsidian", "design system", "components", "clipped", "ui"],
  },
];
